@SaaSBillingApi.Api_HostAddress = http://localhost:5135

GET {{SaaSBillingApi.Api_HostAddress}}/openapi/v1.json
Accept: application/json

###

GET {{SaaSBillingApi.Api_HostAddress}}/weatherforecast/
Accept: application/json

###
